# Generated by Django 3.0.7 on 2020-08-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_appointment_doctorinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorInfo',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='PatientInfo',
            new_name='Patient',
        ),
    ]
