# Generated by Django 3.0.7 on 2020-08-24 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200824_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoint_date',
            field=models.DateTimeField(verbose_name=datetime.date(2020, 8, 24)),
        ),
    ]
