# Generated by Django 3.0.7 on 2020-08-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200824_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
