# Generated by Django 3.1.1 on 2020-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_regnum',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_contact',
            field=models.CharField(max_length=15),
        ),
    ]
