# Generated by Django 3.1 on 2020-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='checkup_id',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_contact',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_symptoms',
            field=models.TextField(default='Symptoms'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_dob',
            field=models.DateField(blank='true'),
        ),
    ]
