# Generated by Django 3.0.7 on 2020-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200905_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='checkup_id',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_contact',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_symptoms',
            field=models.TextField(default='Symptoms'),
        ),
    ]
