# Generated by Django 3.0.7 on 2020-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_firstName', models.CharField(max_length=25)),
                ('patient_middleName', models.CharField(max_length=25)),
                ('patient_lastName', models.CharField(max_length=25)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=1)),
            ],
        ),
    ]
