# Generated by Django 3.0.7 on 2020-08-24 14:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_date', models.DateTimeField(verbose_name=datetime.date(2020, 8, 24))),
                ('appoint_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
